### PR TITLE
[MRG] Elevates scikit-learn warnings to errors

### PR DESCRIPTION
**Pull request by thomasjpfan**
Addresses a piece of #263

This PR elevates warnings to errors.

### CODE REVIEW

**Comment by thomasjpfan** [comment]
Through the use of `nans`, `dask` seems to frequently run into numpys `RuntimeWarnings`: https://github.com/dask/dask/issues/3245 

This PR has been updated to ignore `RuntimeWarnings`.

**Comment by TomAugspurger** [comment]
Thanks.

I'm hoping to solve the LabelEncoder issue (from #333) later today. Sorry about that.

Do you know if there's a way to restrict the elevation to just warnings coming from a specific package (scikit-learn?)

**Comment by TomAugspurger** [comment]
Great, thanks.

It seems to be working properly now. I'll fixup the labelencoder issue the weekend, and we can start to remidy the warnings coming from scikit-learn.

**Comment by thomasjpfan** [comment]
This PR has been updated to address the errors and warnings from `sklearn`. Only `LabelEncoder` related issues are left.

**Comment by TomAugspurger** [comment]
Thanks a ton for doing this. I hope to have the LabelEncoder failure fixed on dask master today.

**Comment by TomAugspurger** [comment]
Merged in master with the labelencoder fix. Hopefully everything passes.

**Comment by TomAugspurger** [comment]
FYI, if you're finding the style checking annoying, I'd recommend installing pre-commit hooks to run it for you: https://dask-ml.readthedocs.io/en/latest/contributing.html#pre-commit-hooks

**Comment by thomasjpfan** [comment]
Thanks for the pre-commit tip! 

There are two DeprecationWarnings appearing in our `dask-ml` tests that are fixed in `sklearn master`. The latest release, `sklearn 0.19.2`, does not contain the commits: https://github.com/scikit-learn/scikit-learn/commit/fe6e562c777179f60e43cca40d86203bf2276178 and https://github.com/scikit-learn/scikit-learn/commit/c554aad456b6302a8dd8838769769eeecc1cf734 that fixes the issue. For now, I choose to ignore the DeprecationWarnings in `dask-ml` tests.

**Comment by TomAugspurger** [comment]
LGTM, thanks!

Just pushed a commit removing some stray `dask-worker-space` files (I have those globally ignored, sorry). Merging on green.

**Comment by thomasjpfan** [comment]
It seems like circleci was having issues earlier today. This may have caused the error in https://circleci.com/gh/dask/dask-ml/1872?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by TomAugspurger** [comment]
I've noticed that test stalling occasionally. Haven't bothered to investigate since it's just python 2.

Thanks again!

**Pull request merged**
