### PR TITLE
Update joblib documentation for scikit-learn 0.20

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by mrocklin** [comment]
It would be nice to add a list at the bottom of common operations within scikit-learn that can benefit from this approach.

**Comment by mrocklin** [comment]
> Also, is there a reason for removing the scatter= section for parallel_backend?

While still available, this feature isn't really necessary any more.  Joblib will automatically detect and scatter data during computation.

**Comment by jrbourbeau** [comment]
Sweet, I hadn't realized that was done automatically. Good to know!

**Comment by TomAugspurger** [comment]
Added a note that this is useful for CPU-bound workloads.

**Pull request merged**
