### PR TITLE
fix: outstanding occurrences of reblock replaced with rechunk

### PR DESCRIPTION
**Pull request by convexset**
I was just exploring the code and noticed the occurrence of reblock in

https://github.com/dask/dask/blob/master/dask/array/learn.py#L71
https://github.com/dask/dask/blob/master/dask/array/learn.py#L101

... I looked for the implementation and couldn't find any, and later found out that it was replaced with rechunk.

See: https://github.com/dask/dask/pull/3570

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks, this apparently isn't tested. Could you add a test that hits it? Something like

```python
X, y = make_classsification(chunks=20)
X = X.rechunk({1: 10})

assert X.numblocks[1] > 1

clf = SGDClassifier()
inc = Incremental(clf)
inc.fit(X, y)
```

**Comment by convexset** [comment]
Hi, sorry, I'll get to this at some point. I've been using my spare time to do stuff in dask/dask/linalg.

**Comment by convexset** [comment]
Done. =)

**Comment by TomAugspurger** [comment]
Thanks @convexset!

**Pull request merged**
