### PR TITLE
MAINT: add distributed as a dependency

### LINKED ISSUE #464: Error importing "IncrementalSearchCV"
```
>>> from dask_ml.model_selection import IncrementalSearchCV
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'IncrementalSearchCV'
```
When I am importing IncrementalSearchCV this is the error, and there is no traceback to track the problem!

### PR DESCRIPTION
**Pull request by stsievert**
Fixes #464

### CODE REVIEW

**Comment by stsievert** [comment]
This is a work in progress while I figure out the testing.

**Comment by TomAugspurger** [comment]
These are generally hard to test in CI, due to module caching.

I'd recommend a simple change at the top of the file with a

```
try:
    import distributed
except ImportError:
    raise ImportError(nice message here)
```

and just a manual test locally in an environment without distributed.

**Comment by jrbourbeau** [comment]
Do we want to add `distributed` as a dependency? Ref discussion going on in #463

**Comment by TomAugspurger** [comment]
I have a slight preference for keeping this an optional dependency for now.

**Comment by jrbourbeau** [comment]
Sounds good

**Comment by TomAugspurger** [comment]
Ahh sorry @stsievert I may have led you astray... I see now why you started with your dummy class, since we need to provide something to `model_selection/__init__.py` to import, so that it would raise when the class is instantiated.

So, given the headaches of working around that, lets just add a dependency on distributed. Did you want to work on that change here?

**Comment by stsievert** [comment]
> So, given the headaches of working around that, lets just add a dependency on distributed. Did you want to work on that change here?

This solution is a lot easier.

I made that change here, which is a one-line change to `setup.py`. Is that all that's required?

> Ahh sorry @stsievert I may have led you astray... I see now why you started with your dummy class

No worries – I didn't waste too much time on this. Plus, dummy classes give a bunch of overhead.

**Comment by TomAugspurger** [comment]
Yeah, the change to setup.py should be all we need now.

I'll take a look at the failing CI in a bit.

**Comment by stsievert** [comment]
Should a minimum version of distributed be required?

**Comment by TomAugspurger** [comment]
I was just looking to see what a good version would be. It seems like distributed 1.25.0 coincides with Dask 1.0, so let's go with that.

**Comment by stsievert** [comment]
Sounds good. I've added `distributed>=1.25.0`. I'll leave leave #461 to make Dask 1.0 required

**Comment by TomAugspurger** [comment]
CI should be fixed now, if you could merge master and push.

**Comment by stsievert** [comment]
Master merged and CI passing.

**Comment by TomAugspurger** [comment]
Thanks.

**Pull request merged**
