### PR TITLE
DOC: mirrors cv note in Scikit-Learn docs for RandomizedSearchCV

### PR DESCRIPTION
**Pull request by stsievert**
**What does this PR implement?**
This is a quick and dirty fix to mirror Scikit-Learn's documentation better.

This resolves an issue I ran into that took about 15 minutes to resolve.

### CODE REVIEW

**Comment by stsievert** [comment]
I think this PR should verify that the Scikit-Learn documentation doesn't have other wording changes.

**Comment by TomAugspurger** [comment]
> I think this PR should verify that the Scikit-Learn documentation doesn't have other wording changes.

What do you mean by this?

**Comment by stsievert** [comment]
> What do you mean by this?

I’d like to check that the Dask-searchcv docs match the sklearn docs

**Comment by stsievert** [comment]
Now most of Dask's RandomizedSearchCV mirrors Scikit-learn's RandomizedSearchCV; this PR should be ready for merge now (almost all the changes are documentation changes).

Most of the doc additions were not relevant to the tests; I've added a small test case for the one relevant test.

**Comment by stsievert** [comment]
All green!

**Comment by TomAugspurger** [comment]
Thanks!

**Pull request merged**
