### PR TITLE
Numpy 1.20 compatibility fixes

### PR DESCRIPTION
**Pull request by jsignell**
closes #784 
Hmmm. Maybe I should have based this off of #782 so that the ci would run....

### CODE REVIEW

**Comment by jsignell** [comment]
I rebased.

**Comment by jsignell** [comment]
If this passes can probably just merge this on rather than #782

**Comment by TomAugspurger** [comment]
Sounds good. I'll merge when it's green.

**Comment by jsignell** [comment]
Hmm looks like linting is also broken. Would you rather merge this and do the lint fix as a follow up?

**Comment by TomAugspurger** [comment]
Here is fine if you're interested in working on it. If so, I'll leave the mypy stuff to you. I'm totally fine with just disabling mypy for now, we aren't getting a ton of value out of it.

**Comment by jsignell** [comment]
I took a look and I think this should merge first so that CI runs on PRs.

**Comment by jsignell** [comment]
The tests are passing other than lint

**Comment by TomAugspurger** [comment]
Great, thanks for this and for opening the issue!

**Pull request merged**
