### PR TITLE
Use dask_sphinx_theme for styling in docs

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
https://travis-ci.org/dask/dask-ml/builds/425863821 is the build that'll be deployed.

**Comment by TomAugspurger** [comment]
Live a ml.dask.org. Things seem to be in good shape.

**Comment by TomAugspurger** [comment]
Huh, the dask logo is missing on http://ml.dask.org/modules/api.html

Haven't investigated why yet.

**Comment by mrocklin** [comment]
It's using a relative rather than absolute path

**Pull request merged**
