### PR TITLE
Miscellaneous joblib updates

### PR DESCRIPTION
**Pull request by jakirkham**
As PR ( https://github.com/joblib/joblib/pull/722 ) added the Distributed backend to Joblib in 0.12.2 and scikit-learn 0.20.0 vendored that joblib version with PR ( https://github.com/scikit-learn/scikit-learn/pull/11741 ), reasonably recent versions of joblib and scikit-learn are already sufficient for our needs here. There may be more room for cleanup following this.

Edit: Also worth noting Distributed 1.24.0 has been raising an `ImportError` when importing `distributed.joblib` ( https://github.com/dask/distributed/pull/2298 ). As we require Distributed 1.25.0 as of PR ( https://github.com/dask/dask-ml/pull/466 ), we've also been raising that same `ImportError` for a while. So it's probably safe to drop the `dask_ml.joblib` shim as well.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks. I have a few CI things to clean up. Will get to this soon.

**Comment by jakirkham** [comment]
No worries. Came across this in some other work I was doing.

**Comment by TomAugspurger** [comment]
Not sure why the doc build is failing, while it's passing on examples.dask.org. Will have to look later.

**Comment by TomAugspurger** [comment]
Thanks John!

**Pull request merged**
