### PR TITLE
Use default scheduler for training

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by mrocklin** [comment]
Long term this should be fixed upstream.  Also, I think that we should move the upstream code in dask/array/learn.py to this repository.

**Comment by TomAugspurger** [comment]
Agreed.

We're actually able to work around this easily by passing `get=client.get` to the `fit` call, so it may just be better to close the PR.

**Comment by mrocklin** [comment]
I'm going to submit a PR moving an updated version of the
dask/array/learn.py code here

**Comment by mrocklin** [comment]
This is now no longer necessary?

**Comment by TomAugspurger** [comment]
Right.

**Pull request closed without merging**
