### PR TITLE
Update `python_requires` to be Python 3.7+

### PR DESCRIPTION
**Pull request by jrbourbeau**
This is a small follow-up to https://github.com/dask/dask-ml/pull/863

Closes https://github.com/dask/dask-ml/issues/942

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks James!

**Comment by jrbourbeau** [comment]
Thanks @TomAugspurger! It looks like GitHub actions didn't run here for some reason...

**Comment by TomAugspurger** [comment]
Whoops. I was pleasantly surprised when I didn't see a failure :)

**Comment by jrbourbeau** [comment]
So there was a run on `main` after this was merged (https://github.com/dask/dask-ml/actions/runs/3283790584) but it looks like the `pull_request` event for this PR didn't trigger a CI run. I'll push an empty PR to see if it's reproducible? 

> Whoops. I was pleasantly surprised when I didn't see a failure :)

I thought it was too good to be true too : )

**Pull request merged**
