### PR TITLE
Change `da.atop` that has been replaced by `da.blockwise` in 

### PR DESCRIPTION
**Pull request by jjerphan**
**Context**:
 - in `dask`, `da.atop` has been replace by `da.blockwise` defined in the same scope — see [dask source](https://github.com/dask/dask/blob/master/dask/array/blockwise.py#L203) ;
 - in `cluster.KMeans`, warnings are thrown because `da.atop` is used ;

**Changes proposed:**
 - replace `da.atop` by `da.blockwise` to remove those warnings ;

### CODE REVIEW

**Comment by jjerphan** [comment]
Oh yes for sure ; I hadn't checked if it was present somewhere else.

As for tests, I guess that those changes aren't related to them failing — as they are on failing others PR's too for the same reasons.

**Comment by jrbourbeau** [comment]
Awesome, thanks! 

You're correct, the failing tests here are unrelated to the changes made in this PR.

**Comment by TomAugspurger** [comment]
I'm hoping to fix the failing CI later today.

**Comment by jjerphan** [comment]
Done @jrbourbeau!

**Comment by TomAugspurger** [comment]
CI should be fixed now, if you could merge master and push.

**Comment by jjerphan** [comment]
Good to go!

**Comment by TomAugspurger** [comment]
Thanks.

**Comment by jrbourbeau** [comment]
@jjerphan I noticed this was your first contribution to dask-ml, welcome!

**Comment by jjerphan** [comment]
Thanks! I may one day contribute on the codebase ; this was rather a small fix and not really a real contribution.

**Comment by jrbourbeau** [comment]
I certainly consider this a useful contribution! Looking forward to future contributions

**Pull request merged**
