### PR TITLE
Add style sheet

### PR DESCRIPTION
**Pull request by mrocklin**
This follows on https://github.com/dask/dask/pull/3360

### CODE REVIEW

**Comment by mrocklin** [comment]
Alternatively we could also just link directly to Dask's style sheet

    app.add_stylesheet('https://dask.pydata.org/en/latest/_static/style.css')

**Comment by jakirkham** [comment]
Do we need this at Dask too? Anywhere else it might be needed?

**Comment by mrocklin** [comment]
This was copied over from Dask.  Did you mean somewhere else?

**Comment by mrocklin** [comment]
> Do we need this at Dask too? Anywhere else it might be needed?

Presumably we might apply this to any of the various downstream libraries.  If we start doing this repeatedly (which might be wise), then I'll suggest that rather than copy around the CSS file as I've done here we instead link to a single version of Dask's stylesheet by placing this line in the source/conf.py file

```python
def setup(...):
    ...
    app.add_stylesheet('https://dask.pydata.org/en/latest/_static/style.css')
```

**Pull request merged**
