### PR TITLE
ENH: ColumnTransformer

### PR DESCRIPTION
**Pull request by TomAugspurger**
This PR implements a daskified column transformer.

There are two issues preventing us from just using scikit-learn's

1. dask DataFrame doesn't implement `.shape` (https://github.com/dask/dask/pull/3212)
2. `sklearn.compose.compose._column_transformer._hstack` doesn't handle dask objects (or pandas dataframes). Just sparse objects and ndarrays. The `_hstack` implemented here handles arrays (dask or numpy) dataframes (dask or numpy) and sparse matricies.

```python
In [1]: import dask.dataframe as dd
   ...: import pandas as pd
   ...: import sklearn.compose
   ...: import sklearn.preprocessing
   ...: from sklearn.base import clone
   ...:
   ...: import dask_ml.compose
   ...: import dask_ml.preprocessing
   ...:
   ...: df = pd.DataFrame({"A": pd.Categorical(["a", "a", "b", "a"]), "B": [1.0, 2, 4, 5]})
   ...: ddf = dd.from_pandas(df, npartitions=2)
   ...:
   ...:

In [2]:     b = dask_ml.compose.make_column_transformer(
   ...:         (["A"], dask_ml.preprocessing.OneHotEncoder(sparse=False)),
   ...:         (["B"], dask_ml.preprocessing.StandardScaler()),
   ...:     )
   ...:
   ...:

In [3]: result = b.fit_transform(ddf)

In [4]: result
Out[4]:
Dask DataFrame Structure:
                   A_a      A_b        B
npartitions=2
0              float64  float64  float64
2                  ...      ...      ...
3                  ...      ...      ...
Dask Name: concat-indexed, 22 tasks

In [5]: result.compute()
Out[5]:
   A_a  A_b         B
0  1.0  0.0 -1.264911
1  1.0  0.0 -0.632456
2  0.0  1.0  0.632456
3  1.0  0.0  1.264911
```

mydask

Long-term, it'd be nice to remove this class entirely, but that'll probably require a lot of work upstream (scipy adopting pydata/sparse, NumPy implementing and libraries adopting `__array_function__`).

Medium-term, `_hstack` could become a staticmethod on `ColumnTransformer`. Then this subclass would just override `_hstack`, and everything else could be removed.

cc @jorisvandenbossche @ogrisel for that last point. Should I open an issue on scikit-learn to discuss that further?

### CODE REVIEW

**Comment by ogrisel** [comment]
> Medium-term, _hstack could become a staticmethod on ColumnTransformer. Then this subclass would just override _hstack, and everything else could be removed.

> cc @jorisvandenbossche @ogrisel for that last point. Should I open an issue on scikit-learn to discuss that further?

+1 for opening an issue on scikit-learn and discuss your suggestion (or even a pull request).

**Comment by ogrisel** [comment]
If you do a quick sklearn PR it could be part of the 0.20 release.

**Comment by TomAugspurger** [comment]
Will do quick.

**Comment by TomAugspurger** [comment]
Scikit-Learn PR at https://github.com/scikit-learn/scikit-learn/pull/11689

This passes locally for me, but won't pass here till https://github.com/dask/dask/pull/3212 and https://github.com/scikit-learn/scikit-learn/pull/11689 are done.

**Comment by TomAugspurger** [comment]
The upstream PRs are in. Merging later today.

**Comment by TomAugspurger** [comment]
Ignoring the coverage failure, since coverage isn't run against sklearn dev.

**Pull request merged**
